var annotated_dup =
[
    [ "ace", "namespaceace.html", [
      [ "detail", "namespaceace_1_1detail.html", [
        [ "sun_controller", "classace_1_1detail_1_1sun__controller.html", "classace_1_1detail_1_1sun__controller" ]
      ] ],
      [ "importer", "namespaceace_1_1importer.html", [
        [ "imported_material", "structace_1_1importer_1_1imported__material.html", "structace_1_1importer_1_1imported__material" ],
        [ "imported_texture", "structace_1_1importer_1_1imported__texture.html", "structace_1_1importer_1_1imported__texture" ]
      ] ],
      [ "rendering", "namespaceace_1_1rendering.html", [
        [ "deferred", "classace_1_1rendering_1_1deferred.html", "classace_1_1rendering_1_1deferred" ],
        [ "lod_data", "structace_1_1rendering_1_1lod__data.html", "structace_1_1rendering_1_1lod__data" ],
        [ "per_camera_data", "structace_1_1rendering_1_1per__camera__data.html", "structace_1_1rendering_1_1per__camera__data" ],
        [ "pipeline", "classace_1_1rendering_1_1pipeline.html", "classace_1_1rendering_1_1pipeline" ]
      ] ],
      [ "shadow", "namespaceace_1_1shadow.html", [
        [ "ClearValues", "structace_1_1shadow_1_1_clear_values.html", "structace_1_1shadow_1_1_clear_values" ],
        [ "DepthImpl", "structace_1_1shadow_1_1_depth_impl.html", "structace_1_1shadow_1_1_depth_impl" ],
        [ "Light", "structace_1_1shadow_1_1_light.html", "structace_1_1shadow_1_1_light" ],
        [ "LightType", "structace_1_1shadow_1_1_light_type.html", "structace_1_1shadow_1_1_light_type" ],
        [ "PackDepth", "structace_1_1shadow_1_1_pack_depth.html", "structace_1_1shadow_1_1_pack_depth" ],
        [ "PosColorTexCoord0Vertex", "structace_1_1shadow_1_1_pos_color_tex_coord0_vertex.html", "structace_1_1shadow_1_1_pos_color_tex_coord0_vertex" ],
        [ "PosNormalTexcoordVertex", "structace_1_1shadow_1_1_pos_normal_texcoord_vertex.html", "structace_1_1shadow_1_1_pos_normal_texcoord_vertex" ],
        [ "PosVertex", "structace_1_1shadow_1_1_pos_vertex.html", "structace_1_1shadow_1_1_pos_vertex" ],
        [ "Programs", "structace_1_1shadow_1_1_programs.html", "structace_1_1shadow_1_1_programs" ],
        [ "ProjType", "structace_1_1shadow_1_1_proj_type.html", "structace_1_1shadow_1_1_proj_type" ],
        [ "RenderState", "structace_1_1shadow_1_1_render_state.html", "structace_1_1shadow_1_1_render_state" ],
        [ "SceneSettings", "structace_1_1shadow_1_1_scene_settings.html", "structace_1_1shadow_1_1_scene_settings" ],
        [ "shadowmap_generator", "classace_1_1shadow_1_1shadowmap__generator.html", "classace_1_1shadow_1_1shadowmap__generator" ],
        [ "ShadowMapRenderTargets", "structace_1_1shadow_1_1_shadow_map_render_targets.html", "structace_1_1shadow_1_1_shadow_map_render_targets" ],
        [ "ShadowMapSettings", "structace_1_1shadow_1_1_shadow_map_settings.html", "structace_1_1shadow_1_1_shadow_map_settings" ],
        [ "SmImpl", "structace_1_1shadow_1_1_sm_impl.html", "structace_1_1shadow_1_1_sm_impl" ],
        [ "SmType", "structace_1_1shadow_1_1_sm_type.html", "structace_1_1shadow_1_1_sm_type" ],
        [ "TetrahedronFaces", "structace_1_1shadow_1_1_tetrahedron_faces.html", "structace_1_1shadow_1_1_tetrahedron_faces" ],
        [ "Uniforms", "structace_1_1shadow_1_1_uniforms.html", "structace_1_1shadow_1_1_uniforms" ]
      ] ],
      [ "animation_channel", "structace_1_1animation__channel.html", "structace_1_1animation__channel" ],
      [ "animation_clip", "structace_1_1animation__clip.html", "structace_1_1animation__clip" ],
      [ "animation_component", "classace_1_1animation__component.html", "classace_1_1animation__component" ],
      [ "animation_panel", "classace_1_1animation__panel.html", "classace_1_1animation__panel" ],
      [ "animation_player", "classace_1_1animation__player.html", "classace_1_1animation__player" ],
      [ "animation_pose", "structace_1_1animation__pose.html", "structace_1_1animation__pose" ],
      [ "animation_state", "structace_1_1animation__state.html", "structace_1_1animation__state" ],
      [ "animation_system", "classace_1_1animation__system.html", "classace_1_1animation__system" ],
      [ "assao_pass", "classace_1_1assao__pass.html", "classace_1_1assao__pass" ],
      [ "asset_database", "classace_1_1asset__database.html", "classace_1_1asset__database" ],
      [ "asset_manager", "classace_1_1asset__manager.html", "classace_1_1asset__manager" ],
      [ "asset_meta", "structace_1_1asset__meta.html", "structace_1_1asset__meta" ],
      [ "asset_storage", "structace_1_1asset__storage.html", "structace_1_1asset__storage" ],
      [ "asset_watcher", "classace_1_1asset__watcher.html", "classace_1_1asset__watcher" ],
      [ "atmospheric_pass", "classace_1_1atmospheric__pass.html", "classace_1_1atmospheric__pass" ],
      [ "atmospheric_pass_perez", "classace_1_1atmospheric__pass__perez.html", "classace_1_1atmospheric__pass__perez" ],
      [ "audio_clip", "structace_1_1audio__clip.html", "structace_1_1audio__clip" ],
      [ "audio_listener_component", "classace_1_1audio__listener__component.html", "classace_1_1audio__listener__component" ],
      [ "audio_source_component", "classace_1_1audio__source__component.html", "classace_1_1audio__source__component" ],
      [ "audio_system", "classace_1_1audio__system.html", "classace_1_1audio__system" ],
      [ "basic_component", "structace_1_1basic__component.html", "structace_1_1basic__component" ],
      [ "basic_storage", "structace_1_1basic__storage.html", "structace_1_1basic__storage" ],
      [ "blend_over_param", "structace_1_1blend__over__param.html", "structace_1_1blend__over__param" ],
      [ "blend_over_time", "structace_1_1blend__over__time.html", "structace_1_1blend__over__time" ],
      [ "blend_space_def", "classace_1_1blend__space__def.html", "classace_1_1blend__space__def" ],
      [ "blend_space_point", "structace_1_1blend__space__point.html", "structace_1_1blend__space__point" ],
      [ "blend_state", "structace_1_1blend__state.html", "structace_1_1blend__state" ],
      [ "bone_component", "structace_1_1bone__component.html", "structace_1_1bone__component" ],
      [ "bone_palette", "classace_1_1bone__palette.html", "classace_1_1bone__palette" ],
      [ "bullet_backend", "structace_1_1bullet__backend.html", "structace_1_1bullet__backend" ],
      [ "camera", "classace_1_1camera.html", "classace_1_1camera" ],
      [ "camera_component", "classace_1_1camera__component.html", "classace_1_1camera__component" ],
      [ "camera_storage", "structace_1_1camera__storage.html", "structace_1_1camera__storage" ],
      [ "camera_system", "classace_1_1camera__system.html", "classace_1_1camera__system" ],
      [ "component_crtp", "structace_1_1component__crtp.html", "structace_1_1component__crtp" ],
      [ "console_log_panel", "classace_1_1console__log__panel.html", "classace_1_1console__log__panel" ],
      [ "content_browser_item", "structace_1_1content__browser__item.html", "structace_1_1content__browser__item" ],
      [ "content_browser_panel", "classace_1_1content__browser__panel.html", "classace_1_1content__browser__panel" ],
      [ "defaults", "structace_1_1defaults.html", "structace_1_1defaults" ],
      [ "deploy", "structace_1_1deploy.html", null ],
      [ "deploy_panel", "classace_1_1deploy__panel.html", "classace_1_1deploy__panel" ],
      [ "deploy_settings", "structace_1_1deploy__settings.html", "structace_1_1deploy__settings" ],
      [ "dockspace", "classace_1_1dockspace.html", "classace_1_1dockspace" ],
      [ "ecs", "structace_1_1ecs.html", "structace_1_1ecs" ],
      [ "editing_manager", "structace_1_1editing__manager.html", "structace_1_1editing__manager" ],
      [ "editor", "structace_1_1editor.html", null ],
      [ "editor_actions", "structace_1_1editor__actions.html", null ],
      [ "engine", "structace_1_1engine.html", null ],
      [ "entity_components", "structace_1_1entity__components.html", "structace_1_1entity__components" ],
      [ "entity_data", "structace_1_1entity__data.html", "structace_1_1entity__data" ],
      [ "entity_panel", "classace_1_1entity__panel.html", "classace_1_1entity__panel" ],
      [ "events", "structace_1_1events.html", "structace_1_1events" ],
      [ "footer_panel", "classace_1_1footer__panel.html", "classace_1_1footer__panel" ],
      [ "game_panel", "classace_1_1game__panel.html", "classace_1_1game__panel" ],
      [ "gizmo", "structace_1_1gizmo.html", "structace_1_1gizmo" ],
      [ "gizmo_entity", "structace_1_1gizmo__entity.html", "structace_1_1gizmo__entity" ],
      [ "gizmo_physics_component", "structace_1_1gizmo__physics__component.html", "structace_1_1gizmo__physics__component" ],
      [ "gizmo_registry", "structace_1_1gizmo__registry.html", "structace_1_1gizmo__registry" ],
      [ "gizmos_renderer", "classace_1_1gizmos__renderer.html", "classace_1_1gizmos__renderer" ],
      [ "gpu_program", "classace_1_1gpu__program.html", "classace_1_1gpu__program" ],
      [ "header_panel", "classace_1_1header__panel.html", "classace_1_1header__panel" ],
      [ "hierarchy_panel", "classace_1_1hierarchy__panel.html", "classace_1_1hierarchy__panel" ],
      [ "hub", "classace_1_1hub.html", "classace_1_1hub" ],
      [ "id_component", "structace_1_1id__component.html", "structace_1_1id__component" ],
      [ "imgui_interface", "classace_1_1imgui__interface.html", "classace_1_1imgui__interface" ],
      [ "imgui_panels", "classace_1_1imgui__panels.html", "classace_1_1imgui__panels" ],
      [ "input_system", "structace_1_1input__system.html", "structace_1_1input__system" ],
      [ "inspect_result", "structace_1_1inspect__result.html", "structace_1_1inspect__result" ],
      [ "inspector", "structace_1_1inspector.html", "structace_1_1inspector" ],
      [ "inspector_asset_handle", "structace_1_1inspector__asset__handle.html", "structace_1_1inspector__asset__handle" ],
      [ "inspector_asset_handle_animation", "structace_1_1inspector__asset__handle__animation.html", "structace_1_1inspector__asset__handle__animation" ],
      [ "inspector_asset_handle_audio_clip", "structace_1_1inspector__asset__handle__audio__clip.html", "structace_1_1inspector__asset__handle__audio__clip" ],
      [ "inspector_asset_handle_material", "structace_1_1inspector__asset__handle__material.html", "structace_1_1inspector__asset__handle__material" ],
      [ "inspector_asset_handle_mesh", "structace_1_1inspector__asset__handle__mesh.html", "structace_1_1inspector__asset__handle__mesh" ],
      [ "inspector_asset_handle_physics_material", "structace_1_1inspector__asset__handle__physics__material.html", "structace_1_1inspector__asset__handle__physics__material" ],
      [ "inspector_asset_handle_prefab", "structace_1_1inspector__asset__handle__prefab.html", "structace_1_1inspector__asset__handle__prefab" ],
      [ "inspector_asset_handle_scene_prefab", "structace_1_1inspector__asset__handle__scene__prefab.html", "structace_1_1inspector__asset__handle__scene__prefab" ],
      [ "inspector_asset_handle_texture", "structace_1_1inspector__asset__handle__texture.html", "structace_1_1inspector__asset__handle__texture" ],
      [ "inspector_bool", "structace_1_1inspector__bool.html", "structace_1_1inspector__bool" ],
      [ "inspector_color", "structace_1_1inspector__color.html", "structace_1_1inspector__color" ],
      [ "inspector_double", "structace_1_1inspector__double.html", "structace_1_1inspector__double" ],
      [ "inspector_duration_sec_double", "structace_1_1inspector__duration__sec__double.html", "structace_1_1inspector__duration__sec__double" ],
      [ "inspector_duration_sec_float", "structace_1_1inspector__duration__sec__float.html", "structace_1_1inspector__duration__sec__float" ],
      [ "inspector_entity", "structace_1_1inspector__entity.html", "structace_1_1inspector__entity" ],
      [ "inspector_float", "structace_1_1inspector__float.html", "structace_1_1inspector__float" ],
      [ "inspector_int16", "structace_1_1inspector__int16.html", "structace_1_1inspector__int16" ],
      [ "inspector_int32", "structace_1_1inspector__int32.html", "structace_1_1inspector__int32" ],
      [ "inspector_int64", "structace_1_1inspector__int64.html", "structace_1_1inspector__int64" ],
      [ "inspector_int8", "structace_1_1inspector__int8.html", "structace_1_1inspector__int8" ],
      [ "inspector_light_component", "structace_1_1inspector__light__component.html", "structace_1_1inspector__light__component" ],
      [ "inspector_mono_object", "structace_1_1inspector__mono__object.html", "structace_1_1inspector__mono__object" ],
      [ "inspector_mono_scoped_object", "structace_1_1inspector__mono__scoped__object.html", null ],
      [ "inspector_panel", "classace_1_1inspector__panel.html", "classace_1_1inspector__panel" ],
      [ "inspector_path", "structace_1_1inspector__path.html", "structace_1_1inspector__path" ],
      [ "inspector_physics_compound_shape", "structace_1_1inspector__physics__compound__shape.html", "structace_1_1inspector__physics__compound__shape" ],
      [ "inspector_quaternion", "structace_1_1inspector__quaternion.html", "structace_1_1inspector__quaternion" ],
      [ "inspector_range_double", "structace_1_1inspector__range__double.html", "structace_1_1inspector__range__double" ],
      [ "inspector_range_float", "structace_1_1inspector__range__float.html", "structace_1_1inspector__range__float" ],
      [ "inspector_range_int16", "structace_1_1inspector__range__int16.html", "structace_1_1inspector__range__int16" ],
      [ "inspector_range_int32", "structace_1_1inspector__range__int32.html", "structace_1_1inspector__range__int32" ],
      [ "inspector_range_int64", "structace_1_1inspector__range__int64.html", "structace_1_1inspector__range__int64" ],
      [ "inspector_range_int8", "structace_1_1inspector__range__int8.html", "structace_1_1inspector__range__int8" ],
      [ "inspector_range_uint16", "structace_1_1inspector__range__uint16.html", "structace_1_1inspector__range__uint16" ],
      [ "inspector_range_uint32", "structace_1_1inspector__range__uint32.html", "structace_1_1inspector__range__uint32" ],
      [ "inspector_range_uint64", "structace_1_1inspector__range__uint64.html", "structace_1_1inspector__range__uint64" ],
      [ "inspector_range_uint8", "structace_1_1inspector__range__uint8.html", "structace_1_1inspector__range__uint8" ],
      [ "inspector_reflection_probe_component", "structace_1_1inspector__reflection__probe__component.html", "structace_1_1inspector__reflection__probe__component" ],
      [ "inspector_registry", "structace_1_1inspector__registry.html", "structace_1_1inspector__registry" ],
      [ "inspector_string", "structace_1_1inspector__string.html", "structace_1_1inspector__string" ],
      [ "inspector_transform", "structace_1_1inspector__transform.html", "structace_1_1inspector__transform" ],
      [ "inspector_uint16", "structace_1_1inspector__uint16.html", "structace_1_1inspector__uint16" ],
      [ "inspector_uint32", "structace_1_1inspector__uint32.html", "structace_1_1inspector__uint32" ],
      [ "inspector_uint64", "structace_1_1inspector__uint64.html", "structace_1_1inspector__uint64" ],
      [ "inspector_uint8", "structace_1_1inspector__uint8.html", "structace_1_1inspector__uint8" ],
      [ "inspector_uuid", "structace_1_1inspector__uuid.html", "structace_1_1inspector__uuid" ],
      [ "inspector_vec2", "structace_1_1inspector__vec2.html", "structace_1_1inspector__vec2" ],
      [ "inspector_vec3", "structace_1_1inspector__vec3.html", "structace_1_1inspector__vec3" ],
      [ "inspector_vec4", "structace_1_1inspector__vec4.html", "structace_1_1inspector__vec4" ],
      [ "light", "structace_1_1light.html", "structace_1_1light" ],
      [ "light_component", "classace_1_1light__component.html", "classace_1_1light__component" ],
      [ "load_context", "structace_1_1load__context.html", "structace_1_1load__context" ],
      [ "log_stopwatch", "structace_1_1log__stopwatch.html", "structace_1_1log__stopwatch" ],
      [ "logging", "structace_1_1logging.html", "structace_1_1logging" ],
      [ "manifold_point", "structace_1_1manifold__point.html", "structace_1_1manifold__point" ],
      [ "material", "classace_1_1material.html", "classace_1_1material" ],
      [ "mesh", "classace_1_1mesh.html", "classace_1_1mesh" ],
      [ "model", "classace_1_1model.html", "classace_1_1model" ],
      [ "model_component", "classace_1_1model__component.html", "classace_1_1model__component" ],
      [ "model_system", "classace_1_1model__system.html", "classace_1_1model__system" ],
      [ "mono_inspector", "structace_1_1mono__inspector.html", null ],
      [ "mono_inspector< asset_handle< T > >", "structace_1_1mono__inspector_3_01asset__handle_3_01_t_01_4_01_4.html", null ],
      [ "mono_inspector< entt::handle >", "structace_1_1mono__inspector_3_01entt_1_1handle_01_4.html", null ],
      [ "mono_loader", "structace_1_1mono__loader.html", null ],
      [ "mono_loader< Archive, asset_handle< T > >", "structace_1_1mono__loader_3_01_archive_00_01asset__handle_3_01_t_01_4_01_4.html", null ],
      [ "mono_loader< Archive, entt::entity >", "structace_1_1mono__loader_3_01_archive_00_01entt_1_1entity_01_4.html", null ],
      [ "mono_saver", "structace_1_1mono__saver.html", null ],
      [ "mono_saver< Archive, asset_handle< T > >", "structace_1_1mono__saver_3_01_archive_00_01asset__handle_3_01_t_01_4_01_4.html", null ],
      [ "mono_saver< Archive, entt::entity >", "structace_1_1mono__saver_3_01_archive_00_01entt_1_1entity_01_4.html", null ],
      [ "named_anim", "structace_1_1named__anim.html", "structace_1_1named__anim" ],
      [ "owned_component", "classace_1_1owned__component.html", "classace_1_1owned__component" ],
      [ "pbr_material", "classace_1_1pbr__material.html", "classace_1_1pbr__material" ],
      [ "performance_profiler", "classace_1_1performance__profiler.html", "classace_1_1performance__profiler" ],
      [ "physics_box_shape", "structace_1_1physics__box__shape.html", "structace_1_1physics__box__shape" ],
      [ "physics_capsule_shape", "structace_1_1physics__capsule__shape.html", "structace_1_1physics__capsule__shape" ],
      [ "physics_component", "classace_1_1physics__component.html", "classace_1_1physics__component" ],
      [ "physics_compound_shape", "structace_1_1physics__compound__shape.html", "structace_1_1physics__compound__shape" ],
      [ "physics_cylinder_shape", "structace_1_1physics__cylinder__shape.html", "structace_1_1physics__cylinder__shape" ],
      [ "physics_material", "structace_1_1physics__material.html", "structace_1_1physics__material" ],
      [ "physics_sphere_shape", "structace_1_1physics__sphere__shape.html", "structace_1_1physics__sphere__shape" ],
      [ "physics_system", "classace_1_1physics__system.html", "classace_1_1physics__system" ],
      [ "picking_manager", "classace_1_1picking__manager.html", "classace_1_1picking__manager" ],
      [ "pipeline_camera", "classace_1_1pipeline__camera.html", "classace_1_1pipeline__camera" ],
      [ "pose_mat4", "structace_1_1pose__mat4.html", "structace_1_1pose__mat4" ],
      [ "pose_transform", "structace_1_1pose__transform.html", "structace_1_1pose__transform" ],
      [ "prefab", "structace_1_1prefab.html", "structace_1_1prefab" ],
      [ "prefab_component", "structace_1_1prefab__component.html", "structace_1_1prefab__component" ],
      [ "project_manager", "classace_1_1project__manager.html", "classace_1_1project__manager" ],
      [ "property_layout", "classace_1_1property__layout.html", "classace_1_1property__layout" ],
      [ "reflection_probe", "structace_1_1reflection__probe.html", "structace_1_1reflection__probe" ],
      [ "reflection_probe_component", "classace_1_1reflection__probe__component.html", "classace_1_1reflection__probe__component" ],
      [ "reflection_probe_system", "classace_1_1reflection__probe__system.html", "classace_1_1reflection__probe__system" ],
      [ "render_window", "structace_1_1render__window.html", "structace_1_1render__window" ],
      [ "renderer", "structace_1_1renderer.html", "structace_1_1renderer" ],
      [ "rendering_system", "classace_1_1rendering__system.html", "classace_1_1rendering__system" ],
      [ "root_component", "structace_1_1root__component.html", null ],
      [ "save_context", "structace_1_1save__context.html", "structace_1_1save__context" ],
      [ "scene", "structace_1_1scene.html", "structace_1_1scene" ],
      [ "scene_panel", "classace_1_1scene__panel.html", "classace_1_1scene__panel" ],
      [ "scene_prefab", "structace_1_1scene__prefab.html", null ],
      [ "scope_perf_timer", "classace_1_1scope__perf__timer.html", "classace_1_1scope__perf__timer" ],
      [ "script", "structace_1_1script.html", "structace_1_1script" ],
      [ "script_component", "classace_1_1script__component.html", "classace_1_1script__component" ],
      [ "script_library", "structace_1_1script__library.html", null ],
      [ "script_system", "structace_1_1script__system.html", "structace_1_1script__system" ],
      [ "settings", "structace_1_1settings.html", "structace_1_1settings" ],
      [ "simulation", "structace_1_1simulation.html", "structace_1_1simulation" ],
      [ "skin_bind_data", "classace_1_1skin__bind__data.html", "classace_1_1skin__bind__data" ],
      [ "skylight_component", "classace_1_1skylight__component.html", "classace_1_1skylight__component" ],
      [ "statistics_panel", "classace_1_1statistics__panel.html", "classace_1_1statistics__panel" ],
      [ "submesh_component", "structace_1_1submesh__component.html", "structace_1_1submesh__component" ],
      [ "tag_component", "structace_1_1tag__component.html", "structace_1_1tag__component" ],
      [ "test_component", "structace_1_1test__component.html", "structace_1_1test__component" ],
      [ "threader", "structace_1_1threader.html", "structace_1_1threader" ],
      [ "thumbnail_manager", "structace_1_1thumbnail__manager.html", "structace_1_1thumbnail__manager" ],
      [ "tonemapping_pass", "classace_1_1tonemapping__pass.html", "classace_1_1tonemapping__pass" ],
      [ "transform_component", "classace_1_1transform__component.html", "classace_1_1transform__component" ],
      [ "transform_system", "classace_1_1transform__system.html", "classace_1_1transform__system" ],
      [ "ui_events", "structace_1_1ui__events.html", "structace_1_1ui__events" ],
      [ "uniforms_cache", "structace_1_1uniforms__cache.html", "structace_1_1uniforms__cache" ],
      [ "var_info", "structace_1_1var__info.html", "structace_1_1var__info" ]
    ] ],
    [ "cmd_line", "namespacecmd__line.html", [
      [ "callback_args", "structcmd__line_1_1callback__args.html", "structcmd__line_1_1callback__args" ],
      [ "numeric_base", "classcmd__line_1_1numeric__base.html", "classcmd__line_1_1numeric__base" ],
      [ "parser", "classcmd__line_1_1parser.html", "classcmd__line_1_1parser" ]
    ] ],
    [ "fs", "namespacefs.html", [
      [ "cache", "classfs_1_1cache.html", "classfs_1_1cache" ],
      [ "stream_buffer", "structfs_1_1stream__buffer.html", "structfs_1_1stream__buffer" ],
      [ "syncer", "classfs_1_1syncer.html", "classfs_1_1syncer" ],
      [ "watcher", "classfs_1_1watcher.html", "classfs_1_1watcher" ]
    ] ],
    [ "GenerateIconFontCppHeaders", "namespace_generate_icon_font_cpp_headers.html", [
      [ "Font", "class_generate_icon_font_cpp_headers_1_1_font.html", "class_generate_icon_font_cpp_headers_1_1_font" ],
      [ "FontFA4", "class_generate_icon_font_cpp_headers_1_1_font_f_a4.html", "class_generate_icon_font_cpp_headers_1_1_font_f_a4" ],
      [ "FontFA5", "class_generate_icon_font_cpp_headers_1_1_font_f_a5.html", "class_generate_icon_font_cpp_headers_1_1_font_f_a5" ],
      [ "FontFA5Brands", "class_generate_icon_font_cpp_headers_1_1_font_f_a5_brands.html", "class_generate_icon_font_cpp_headers_1_1_font_f_a5_brands" ],
      [ "FontFK", "class_generate_icon_font_cpp_headers_1_1_font_f_k.html", null ],
      [ "FontII", "class_generate_icon_font_cpp_headers_1_1_font_i_i.html", "class_generate_icon_font_cpp_headers_1_1_font_i_i" ],
      [ "FontKI", "class_generate_icon_font_cpp_headers_1_1_font_k_i.html", "class_generate_icon_font_cpp_headers_1_1_font_k_i" ],
      [ "FontMD", "class_generate_icon_font_cpp_headers_1_1_font_m_d.html", "class_generate_icon_font_cpp_headers_1_1_font_m_d" ],
      [ "FontMDI", "class_generate_icon_font_cpp_headers_1_1_font_m_d_i.html", "class_generate_icon_font_cpp_headers_1_1_font_m_d_i" ],
      [ "Language", "class_generate_icon_font_cpp_headers_1_1_language.html", "class_generate_icon_font_cpp_headers_1_1_language" ],
      [ "LanguageC89", "class_generate_icon_font_cpp_headers_1_1_language_c89.html", "class_generate_icon_font_cpp_headers_1_1_language_c89" ],
      [ "LanguageCpp11", "class_generate_icon_font_cpp_headers_1_1_language_cpp11.html", "class_generate_icon_font_cpp_headers_1_1_language_cpp11" ],
      [ "LanguageCSharp", "class_generate_icon_font_cpp_headers_1_1_language_c_sharp.html", "class_generate_icon_font_cpp_headers_1_1_language_c_sharp" ]
    ] ],
    [ "generator", "namespacegenerator.html", [
      [ "detail", "namespacegenerator_1_1detail.html", [
        [ "box_corner_t", "classgenerator_1_1detail_1_1box__corner__t.html", "classgenerator_1_1detail_1_1box__corner__t" ],
        [ "box_corners_t", "classgenerator_1_1detail_1_1box__corners__t.html", "classgenerator_1_1detail_1_1box__corners__t" ],
        [ "box_edge_t", "classgenerator_1_1detail_1_1box__edge__t.html", "classgenerator_1_1detail_1_1box__edge__t" ],
        [ "box_edges_t", "classgenerator_1_1detail_1_1box__edges__t.html", "classgenerator_1_1detail_1_1box__edges__t" ],
        [ "box_face_t", "classgenerator_1_1detail_1_1box__face__t.html", "classgenerator_1_1detail_1_1box__face__t" ],
        [ "box_faces_t", "classgenerator_1_1detail_1_1box__faces__t.html", "classgenerator_1_1detail_1_1box__faces__t" ],
        [ "cap_t", "classgenerator_1_1detail_1_1cap__t.html", "classgenerator_1_1detail_1_1cap__t" ],
        [ "tube_cap_t", "classgenerator_1_1detail_1_1tube__cap__t.html", "classgenerator_1_1detail_1_1tube__cap__t" ]
      ] ],
      [ "any_generator", "classgenerator_1_1any__generator.html", "classgenerator_1_1any__generator" ],
      [ "any_mesh", "classgenerator_1_1any__mesh.html", "classgenerator_1_1any__mesh" ],
      [ "any_path", "classgenerator_1_1any__path.html", "classgenerator_1_1any__path" ],
      [ "any_shape", "classgenerator_1_1any__shape.html", "classgenerator_1_1any__shape" ],
      [ "axis_flip_mesh_t", "classgenerator_1_1axis__flip__mesh__t.html", "classgenerator_1_1axis__flip__mesh__t" ],
      [ "axis_swap_mesh_t", "classgenerator_1_1axis__swap__mesh__t.html", "classgenerator_1_1axis__swap__mesh__t" ],
      [ "axis_swap_path_t", "classgenerator_1_1axis__swap__path__t.html", "classgenerator_1_1axis__swap__path__t" ],
      [ "axis_swap_shape_t", "classgenerator_1_1axis__swap__shape__t.html", "classgenerator_1_1axis__swap__shape__t" ],
      [ "bezier_mesh_t", "classgenerator_1_1bezier__mesh__t.html", "classgenerator_1_1bezier__mesh__t" ],
      [ "bezier_shape_t", "classgenerator_1_1bezier__shape__t.html", "classgenerator_1_1bezier__shape__t" ],
      [ "box_mesh_t", "classgenerator_1_1box__mesh__t.html", "classgenerator_1_1box__mesh__t" ],
      [ "capped_cone_mesh_t", "classgenerator_1_1capped__cone__mesh__t.html", "classgenerator_1_1capped__cone__mesh__t" ],
      [ "capped_cylinder_mesh_t", "classgenerator_1_1capped__cylinder__mesh__t.html", "classgenerator_1_1capped__cylinder__mesh__t" ],
      [ "capped_tube_mesh_t", "classgenerator_1_1capped__tube__mesh__t.html", "classgenerator_1_1capped__tube__mesh__t" ],
      [ "capsule_mesh_t", "classgenerator_1_1capsule__mesh__t.html", "classgenerator_1_1capsule__mesh__t" ],
      [ "circle_shape_t", "classgenerator_1_1circle__shape__t.html", "classgenerator_1_1circle__shape__t" ],
      [ "cone_mesh_t", "classgenerator_1_1cone__mesh__t.html", "classgenerator_1_1cone__mesh__t" ],
      [ "convex_polygon_mesh_t", "classgenerator_1_1convex__polygon__mesh__t.html", "classgenerator_1_1convex__polygon__mesh__t" ],
      [ "cylinder_mesh_t", "classgenerator_1_1cylinder__mesh__t.html", "classgenerator_1_1cylinder__mesh__t" ],
      [ "disk_mesh_t", "classgenerator_1_1disk__mesh__t.html", "classgenerator_1_1disk__mesh__t" ],
      [ "dodecahedron_mesh_t", "classgenerator_1_1dodecahedron__mesh__t.html", "classgenerator_1_1dodecahedron__mesh__t" ],
      [ "edge_generator_type", "classgenerator_1_1edge__generator__type.html", "classgenerator_1_1edge__generator__type" ],
      [ "edge_t", "classgenerator_1_1edge__t.html", "classgenerator_1_1edge__t" ],
      [ "empty_mesh", "classgenerator_1_1empty__mesh.html", "classgenerator_1_1empty__mesh" ],
      [ "empty_path_t", "classgenerator_1_1empty__path__t.html", "classgenerator_1_1empty__path__t" ],
      [ "empty_shape_t", "classgenerator_1_1empty__shape__t.html", "classgenerator_1_1empty__shape__t" ],
      [ "extrude_mesh_t", "classgenerator_1_1extrude__mesh__t.html", "classgenerator_1_1extrude__mesh__t" ],
      [ "flip_mesh_t", "classgenerator_1_1flip__mesh__t.html", "classgenerator_1_1flip__mesh__t" ],
      [ "flip_path_t", "classgenerator_1_1flip__path__t.html", "classgenerator_1_1flip__path__t" ],
      [ "flip_shape_t", "classgenerator_1_1flip__shape__t.html", "classgenerator_1_1flip__shape__t" ],
      [ "generated_type", "classgenerator_1_1generated__type.html", "classgenerator_1_1generated__type" ],
      [ "grid_shape_t", "classgenerator_1_1grid__shape__t.html", "classgenerator_1_1grid__shape__t" ],
      [ "helix_path_t", "classgenerator_1_1helix__path__t.html", "classgenerator_1_1helix__path__t" ],
      [ "ico_sphere_mesh_t", "classgenerator_1_1ico__sphere__mesh__t.html", "classgenerator_1_1ico__sphere__mesh__t" ],
      [ "icosahedron_mesh_t", "classgenerator_1_1icosahedron__mesh__t.html", "classgenerator_1_1icosahedron__mesh__t" ],
      [ "iterator_t", "classgenerator_1_1iterator__t.html", "classgenerator_1_1iterator__t" ],
      [ "knot_path_t", "classgenerator_1_1knot__path__t.html", "classgenerator_1_1knot__path__t" ],
      [ "lathe_mesh_t", "classgenerator_1_1lathe__mesh__t.html", "classgenerator_1_1lathe__mesh__t" ],
      [ "line_path_t", "classgenerator_1_1line__path__t.html", "classgenerator_1_1line__path__t" ],
      [ "line_shape_t", "classgenerator_1_1line__shape__t.html", "classgenerator_1_1line__shape__t" ],
      [ "merge_mesh_t", "classgenerator_1_1merge__mesh__t.html", null ],
      [ "merge_mesh_t< Head, Tail... >", "classgenerator_1_1merge__mesh__t_3_01_head_00_01_tail_8_8_8_01_4.html", "classgenerator_1_1merge__mesh__t_3_01_head_00_01_tail_8_8_8_01_4" ],
      [ "merge_mesh_t<>", "classgenerator_1_1merge__mesh__t_3_4.html", null ],
      [ "merge_path_t", "classgenerator_1_1merge__path__t.html", null ],
      [ "merge_path_t< Head, Tail... >", "classgenerator_1_1merge__path__t_3_01_head_00_01_tail_8_8_8_01_4.html", "classgenerator_1_1merge__path__t_3_01_head_00_01_tail_8_8_8_01_4" ],
      [ "merge_path_t<>", "classgenerator_1_1merge__path__t_3_4.html", null ],
      [ "merge_shape_t", "classgenerator_1_1merge__shape__t.html", null ],
      [ "merge_shape_t< Head, Tail... >", "classgenerator_1_1merge__shape__t_3_01_head_00_01_tail_8_8_8_01_4.html", "classgenerator_1_1merge__shape__t_3_01_head_00_01_tail_8_8_8_01_4" ],
      [ "merge_shape_t<>", "classgenerator_1_1merge__shape__t_3_4.html", null ],
      [ "mesh_vertex_t", "classgenerator_1_1mesh__vertex__t.html", "classgenerator_1_1mesh__vertex__t" ],
      [ "mirror_mesh_t", "classgenerator_1_1mirror__mesh__t.html", "classgenerator_1_1mirror__mesh__t" ],
      [ "obj_writer_t", "classgenerator_1_1obj__writer__t.html", "classgenerator_1_1obj__writer__t" ],
      [ "parametric_mesh_t", "classgenerator_1_1parametric__mesh__t.html", "classgenerator_1_1parametric__mesh__t" ],
      [ "parametric_path_t", "classgenerator_1_1parametric__path__t.html", "classgenerator_1_1parametric__path__t" ],
      [ "parametric_shape_t", "classgenerator_1_1parametric__shape__t.html", "classgenerator_1_1parametric__shape__t" ],
      [ "path_vertex_t", "classgenerator_1_1path__vertex__t.html", "classgenerator_1_1path__vertex__t" ],
      [ "plane_mesh_t", "classgenerator_1_1plane__mesh__t.html", "classgenerator_1_1plane__mesh__t" ],
      [ "rectangle_shape_t", "classgenerator_1_1rectangle__shape__t.html", "classgenerator_1_1rectangle__shape__t" ],
      [ "repeat_mesh_t", "classgenerator_1_1repeat__mesh__t.html", "classgenerator_1_1repeat__mesh__t" ],
      [ "repeat_path_t", "classgenerator_1_1repeat__path__t.html", "classgenerator_1_1repeat__path__t" ],
      [ "repeat_shape_t", "classgenerator_1_1repeat__shape__t.html", "classgenerator_1_1repeat__shape__t" ],
      [ "rotate_mesh_t", "classgenerator_1_1rotate__mesh__t.html", "classgenerator_1_1rotate__mesh__t" ],
      [ "rotate_path_t", "classgenerator_1_1rotate__path__t.html", "classgenerator_1_1rotate__path__t" ],
      [ "rotate_shape_t", "classgenerator_1_1rotate__shape__t.html", "classgenerator_1_1rotate__shape__t" ],
      [ "rounded_box_mesh_t", "classgenerator_1_1rounded__box__mesh__t.html", "classgenerator_1_1rounded__box__mesh__t" ],
      [ "rounded_rectangle_shape_t", "classgenerator_1_1rounded__rectangle__shape__t.html", "classgenerator_1_1rounded__rectangle__shape__t" ],
      [ "scale_mesh_t", "classgenerator_1_1scale__mesh__t.html", "classgenerator_1_1scale__mesh__t" ],
      [ "scale_path_t", "classgenerator_1_1scale__path__t.html", "classgenerator_1_1scale__path__t" ],
      [ "scale_shape_t", "classgenerator_1_1scale__shape__t.html", "classgenerator_1_1scale__shape__t" ],
      [ "shape_to_path_t", "classgenerator_1_1shape__to__path__t.html", "classgenerator_1_1shape__to__path__t" ],
      [ "shape_vertex_t", "classgenerator_1_1shape__vertex__t.html", "classgenerator_1_1shape__vertex__t" ],
      [ "sphere_mesh_t", "classgenerator_1_1sphere__mesh__t.html", "classgenerator_1_1sphere__mesh__t" ],
      [ "spherical_cone_mesh_t", "classgenerator_1_1spherical__cone__mesh__t.html", "classgenerator_1_1spherical__cone__mesh__t" ],
      [ "spherical_triangle_mesh_t", "classgenerator_1_1spherical__triangle__mesh__t.html", "classgenerator_1_1spherical__triangle__mesh__t" ],
      [ "spherify_mesh_t", "classgenerator_1_1spherify__mesh__t.html", "classgenerator_1_1spherify__mesh__t" ],
      [ "spring_mesh_t", "classgenerator_1_1spring__mesh__t.html", "classgenerator_1_1spring__mesh__t" ],
      [ "subdivide_mesh_t", "classgenerator_1_1subdivide__mesh__t.html", "classgenerator_1_1subdivide__mesh__t" ],
      [ "subdivide_mesh_t< mesh_t, 0 >", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_010_01_4.html", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_010_01_4" ],
      [ "subdivide_mesh_t< mesh_t, 1 >", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_011_01_4.html", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_011_01_4" ],
      [ "subdivide_path_t", "classgenerator_1_1subdivide__path__t.html", "classgenerator_1_1subdivide__path__t" ],
      [ "subdivide_shape_t", "classgenerator_1_1subdivide__shape__t.html", "classgenerator_1_1subdivide__shape__t" ],
      [ "svg_writer_t", "classgenerator_1_1svg__writer__t.html", "classgenerator_1_1svg__writer__t" ],
      [ "teapot_mesh_t", "classgenerator_1_1teapot__mesh__t.html", "classgenerator_1_1teapot__mesh__t" ],
      [ "torus_knot_mesh_t", "classgenerator_1_1torus__knot__mesh__t.html", "classgenerator_1_1torus__knot__mesh__t" ],
      [ "torus_mesh_t", "classgenerator_1_1torus__mesh__t.html", "classgenerator_1_1torus__mesh__t" ],
      [ "transform_mesh_t", "classgenerator_1_1transform__mesh__t.html", "classgenerator_1_1transform__mesh__t" ],
      [ "transform_path_t", "classgenerator_1_1transform__path__t.html", "classgenerator_1_1transform__path__t" ],
      [ "transform_shape_t", "classgenerator_1_1transform__shape__t.html", "classgenerator_1_1transform__shape__t" ],
      [ "translate_mesh_t", "classgenerator_1_1translate__mesh__t.html", "classgenerator_1_1translate__mesh__t" ],
      [ "translate_path_t", "classgenerator_1_1translate__path__t.html", "classgenerator_1_1translate__path__t" ],
      [ "translate_shape_t", "classgenerator_1_1translate__shape__t.html", "classgenerator_1_1translate__shape__t" ],
      [ "triangle_generator_type", "classgenerator_1_1triangle__generator__type.html", "classgenerator_1_1triangle__generator__type" ],
      [ "triangle_mesh_t", "classgenerator_1_1triangle__mesh__t.html", "classgenerator_1_1triangle__mesh__t" ],
      [ "triangle_t", "classgenerator_1_1triangle__t.html", "classgenerator_1_1triangle__t" ],
      [ "tube_mesh_t", "classgenerator_1_1tube__mesh__t.html", "classgenerator_1_1tube__mesh__t" ],
      [ "uv_flip_mesh_t", "classgenerator_1_1uv__flip__mesh__t.html", "classgenerator_1_1uv__flip__mesh__t" ],
      [ "uv_swap_mesh_t", "classgenerator_1_1uv__swap__mesh__t.html", "classgenerator_1_1uv__swap__mesh__t" ],
      [ "vertex_generator_type", "classgenerator_1_1vertex__generator__type.html", "classgenerator_1_1vertex__generator__type" ]
    ] ],
    [ "gfx", "namespacegfx.html", [
      [ "dd_raii", "structgfx_1_1dd__raii.html", "structgfx_1_1dd__raii" ],
      [ "fbo_attachment", "structgfx_1_1fbo__attachment.html", "structgfx_1_1fbo__attachment" ],
      [ "fbo_key", "structgfx_1_1fbo__key.html", "structgfx_1_1fbo__key" ],
      [ "frame_buffer", "structgfx_1_1frame__buffer.html", "structgfx_1_1frame__buffer" ],
      [ "gfx_callback", "structgfx_1_1gfx__callback.html", "structgfx_1_1gfx__callback" ],
      [ "handle_impl", "classgfx_1_1handle__impl.html", "classgfx_1_1handle__impl" ],
      [ "index_buffer", "structgfx_1_1index__buffer.html", "structgfx_1_1index__buffer" ],
      [ "mesh_vertex", "structgfx_1_1mesh__vertex.html", null ],
      [ "pos_texcoord0_color0_vertex", "structgfx_1_1pos__texcoord0__color0__vertex.html", null ],
      [ "pos_texcoord0_vertex", "structgfx_1_1pos__texcoord0__vertex.html", "structgfx_1_1pos__texcoord0__vertex" ],
      [ "pos_vertex", "structgfx_1_1pos__vertex.html", "structgfx_1_1pos__vertex" ],
      [ "program", "structgfx_1_1program.html", "structgfx_1_1program" ],
      [ "render_pass", "structgfx_1_1render__pass.html", "structgfx_1_1render__pass" ],
      [ "render_view", "classgfx_1_1render__view.html", "classgfx_1_1render__view" ],
      [ "screen_pos_vertex", "structgfx_1_1screen__pos__vertex.html", "structgfx_1_1screen__pos__vertex" ],
      [ "shader", "structgfx_1_1shader.html", "structgfx_1_1shader" ],
      [ "texture", "structgfx_1_1texture.html", "structgfx_1_1texture" ],
      [ "texture_key", "structgfx_1_1texture__key.html", "structgfx_1_1texture__key" ],
      [ "uniform", "structgfx_1_1uniform.html", "structgfx_1_1uniform" ],
      [ "vertex", "structgfx_1_1vertex.html", null ],
      [ "vertex_buffer", "structgfx_1_1vertex__buffer.html", "structgfx_1_1vertex__buffer" ]
    ] ],
    [ "glm", "namespaceglm.html", [
      [ "detail", "namespaceglm_1_1detail.html", [
        [ "compute_to_string< math::transform_t< T, Q > >", "structglm_1_1detail_1_1compute__to__string_3_01math_1_1transform__t_3_01_t_00_01_q_01_4_01_4.html", null ]
      ] ]
    ] ],
    [ "gml", "namespacegml.html", [
      [ "detail", "namespacegml_1_1detail.html", [
        [ "bezierDerivativeImpl", "structgml_1_1detail_1_1bezier_derivative_impl.html", null ],
        [ "bezierDerivativeImpl< 0, 1, VecT, T >", "structgml_1_1detail_1_1bezier_derivative_impl_3_010_00_011_00_01_vec_t_00_01_t_01_4.html", null ],
        [ "bezierDerivativeImpl< 0, D, VecT, T >", "structgml_1_1detail_1_1bezier_derivative_impl_3_010_00_01_d_00_01_vec_t_00_01_t_01_4.html", null ],
        [ "bezierDerivativeImpl< O, 1, VecT, T >", "structgml_1_1detail_1_1bezier_derivative_impl_3_01_o_00_011_00_01_vec_t_00_01_t_01_4.html", null ]
      ] ]
    ] ],
    [ "helper", "namespacehelper.html", [
      [ "is_chrono_duration", "structhelper_1_1is__chrono__duration.html", null ],
      [ "is_chrono_duration< std::chrono::duration< R, P > >", "structhelper_1_1is__chrono__duration_3_01std_1_1chrono_1_1duration_3_01_r_00_01_p_01_4_01_4.html", null ]
    ] ],
    [ "ImGui", "namespace_im_gui.html", [
      [ "Font", "struct_im_gui_1_1_font.html", "struct_im_gui_1_1_font" ],
      [ "ImTexture", "union_im_gui_1_1_im_texture.html", "union_im_gui_1_1_im_texture" ]
    ] ],
    [ "input", "namespaceinput.html", [
      [ "action_map", "classinput_1_1action__map.html", "classinput_1_1action__map" ],
      [ "bimap", "classinput_1_1bimap.html", "classinput_1_1bimap" ],
      [ "button_state_map", "classinput_1_1button__state__map.html", "classinput_1_1button__state__map" ],
      [ "coord", "structinput_1_1coord.html", "structinput_1_1coord" ],
      [ "gamepad", "classinput_1_1gamepad.html", "classinput_1_1gamepad" ],
      [ "Gamepad360", "classinput_1_1_gamepad360.html", null ],
      [ "gamepad_action_map", "classinput_1_1gamepad__action__map.html", "classinput_1_1gamepad__action__map" ],
      [ "input_device", "classinput_1_1input__device.html", "classinput_1_1input__device" ],
      [ "input_manager", "classinput_1_1input__manager.html", "classinput_1_1input__manager" ],
      [ "key_state_map", "classinput_1_1key__state__map.html", "classinput_1_1key__state__map" ],
      [ "keyboard", "classinput_1_1keyboard.html", "classinput_1_1keyboard" ],
      [ "keyboard_action_map", "classinput_1_1keyboard__action__map.html", "classinput_1_1keyboard__action__map" ],
      [ "mouse", "classinput_1_1mouse.html", "classinput_1_1mouse" ],
      [ "mouse_action_map", "classinput_1_1mouse__action__map.html", "classinput_1_1mouse__action__map" ],
      [ "os_gamepad", "classinput_1_1os__gamepad.html", "classinput_1_1os__gamepad" ],
      [ "os_input_manager", "classinput_1_1os__input__manager.html", "classinput_1_1os__input__manager" ],
      [ "os_keyboard", "classinput_1_1os__keyboard.html", "classinput_1_1os__keyboard" ],
      [ "os_mouse", "classinput_1_1os__mouse.html", "classinput_1_1os__mouse" ],
      [ "point", "structinput_1_1point.html", "structinput_1_1point" ]
    ] ],
    [ "math", "namespacemath.html", [
      [ "bbox", "structmath_1_1bbox.html", "structmath_1_1bbox" ],
      [ "bsphere", "classmath_1_1bsphere.html", "classmath_1_1bsphere" ],
      [ "color", "structmath_1_1color.html", "structmath_1_1color" ],
      [ "frustum", "classmath_1_1frustum.html", "classmath_1_1frustum" ],
      [ "plane", "structmath_1_1plane.html", "structmath_1_1plane" ],
      [ "transform_t", "classmath_1_1transform__t.html", "classmath_1_1transform__t" ]
    ] ],
    [ "mono", "namespacemono.html", [
      [ "managed_interface", "namespacemono_1_1managed__interface.html", [
        [ "quaternion", "structmono_1_1managed__interface_1_1quaternion.html", "structmono_1_1managed__interface_1_1quaternion" ],
        [ "vector2", "structmono_1_1managed__interface_1_1vector2.html", "structmono_1_1managed__interface_1_1vector2" ],
        [ "vector3", "structmono_1_1managed__interface_1_1vector3.html", "structmono_1_1managed__interface_1_1vector3" ],
        [ "vector4", "structmono_1_1managed__interface_1_1vector4.html", "structmono_1_1managed__interface_1_1vector4" ]
      ] ]
    ] ],
    [ "rtti", "namespacertti.html", [
      [ "context", "structrtti_1_1context.html", "structrtti_1_1context" ]
    ] ],
    [ "ser20", "namespaceser20.html", [
      [ "variant_detail", "namespaceser20_1_1variant__detail.html", [
        [ "variant_save_visitor", "structser20_1_1variant__detail_1_1variant__save__visitor.html", "structser20_1_1variant__detail_1_1variant__save__visitor" ]
      ] ],
      [ "basic_handle_link", "structser20_1_1basic__handle__link.html", "structser20_1_1basic__handle__link" ],
      [ "const_entity_handle_link", "structser20_1_1const__entity__handle__link.html", null ],
      [ "entity_handle_link", "structser20_1_1entity__handle__link.html", null ],
      [ "membuf", "classser20_1_1membuf.html", "classser20_1_1membuf" ],
      [ "YAMLInputArchive", "classser20_1_1_y_a_m_l_input_archive.html", "classser20_1_1_y_a_m_l_input_archive" ],
      [ "YAMLOutputArchive", "classser20_1_1_y_a_m_l_output_archive.html", "classser20_1_1_y_a_m_l_output_archive" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< gfx::fbo_key >", "structstd_1_1hash_3_01gfx_1_1fbo__key_01_4.html", "structstd_1_1hash_3_01gfx_1_1fbo__key_01_4" ],
      [ "hash< gfx::texture_key >", "structstd_1_1hash_3_01gfx_1_1texture__key_01_4.html", "structstd_1_1hash_3_01gfx_1_1texture__key_01_4" ]
    ] ],
    [ "subprocess", "namespacesubprocess.html", [
      [ "detail", "namespacesubprocess_1_1detail.html", [
        [ "ArgumentDeducer", "structsubprocess_1_1detail_1_1_argument_deducer.html", "structsubprocess_1_1detail_1_1_argument_deducer" ],
        [ "Child", "classsubprocess_1_1detail_1_1_child.html", "classsubprocess_1_1detail_1_1_child" ],
        [ "Communication", "classsubprocess_1_1detail_1_1_communication.html", "classsubprocess_1_1detail_1_1_communication" ],
        [ "has_type", "structsubprocess_1_1detail_1_1has__type.html", null ],
        [ "has_type< F, param_pack< F, T... > >", "structsubprocess_1_1detail_1_1has__type_3_01_f_00_01param__pack_3_01_f_00_01_t_8_8_8_01_4_01_4.html", null ],
        [ "has_type< F, param_pack< H, T... > >", "structsubprocess_1_1detail_1_1has__type_3_01_f_00_01param__pack_3_01_h_00_01_t_8_8_8_01_4_01_4.html", null ],
        [ "has_type< F, param_pack<> >", "structsubprocess_1_1detail_1_1has__type_3_01_f_00_01param__pack_3_4_01_4.html", null ],
        [ "param_pack", "structsubprocess_1_1detail_1_1param__pack.html", null ],
        [ "Streams", "classsubprocess_1_1detail_1_1_streams.html", "classsubprocess_1_1detail_1_1_streams" ]
      ] ],
      [ "Buffer", "classsubprocess_1_1_buffer.html", "classsubprocess_1_1_buffer" ],
      [ "bufsize", "structsubprocess_1_1bufsize.html", "structsubprocess_1_1bufsize" ],
      [ "call_result", "structsubprocess_1_1call__result.html", "structsubprocess_1_1call__result" ],
      [ "CalledProcessError", "classsubprocess_1_1_called_process_error.html", "classsubprocess_1_1_called_process_error" ],
      [ "close_fds", "structsubprocess_1_1close__fds.html", "structsubprocess_1_1close__fds" ],
      [ "cwd", "structsubprocess_1_1cwd.html", "structsubprocess_1_1cwd" ],
      [ "defer_spawn", "structsubprocess_1_1defer__spawn.html", "structsubprocess_1_1defer__spawn" ],
      [ "environment", "structsubprocess_1_1environment.html", "structsubprocess_1_1environment" ],
      [ "error", "structsubprocess_1_1error.html", "structsubprocess_1_1error" ],
      [ "executable", "structsubprocess_1_1executable.html", "structsubprocess_1_1executable" ],
      [ "input", "structsubprocess_1_1input.html", "structsubprocess_1_1input" ],
      [ "OSError", "classsubprocess_1_1_o_s_error.html", "classsubprocess_1_1_o_s_error" ],
      [ "output", "structsubprocess_1_1output.html", "structsubprocess_1_1output" ],
      [ "Popen", "classsubprocess_1_1_popen.html", "classsubprocess_1_1_popen" ],
      [ "preexec_func", "classsubprocess_1_1preexec__func.html", "classsubprocess_1_1preexec__func" ],
      [ "session_leader", "structsubprocess_1_1session__leader.html", "structsubprocess_1_1session__leader" ],
      [ "shell", "structsubprocess_1_1shell.html", "structsubprocess_1_1shell" ],
      [ "string_arg", "structsubprocess_1_1string__arg.html", "structsubprocess_1_1string__arg" ]
    ] ],
    [ "tweeny", "namespacetweeny.html", [
      [ "tween_action", "structtweeny_1_1tween__action.html", "structtweeny_1_1tween__action" ],
      [ "tween_inspect_info", "structtweeny_1_1tween__inspect__info.html", "structtweeny_1_1tween__inspect__info" ],
      [ "tween_manager", "structtweeny_1_1tween__manager.html", "structtweeny_1_1tween__manager" ],
      [ "tween_private", "structtweeny_1_1tween__private.html", null ],
      [ "tween_scope_policy", "structtweeny_1_1tween__scope__policy.html", "structtweeny_1_1tween__scope__policy" ],
      [ "values_t", "structtweeny_1_1values__t.html", "structtweeny_1_1values__t" ]
    ] ],
    [ "asset_handle", "structasset__handle.html", "structasset__handle" ],
    [ "asset_link", "structasset__link.html", "structasset__link" ],
    [ "Atlas", "class_atlas.html", "class_atlas" ],
    [ "AtlasRegion", "struct_atlas_region.html", "struct_atlas_region" ],
    [ "Attrib", "struct_attrib.html", "struct_attrib" ],
    [ "AviWriter", "struct_avi_writer.html", "struct_avi_writer" ],
    [ "Axis", "struct_axis.html", "struct_axis" ],
    [ "checked_array_deleter", "structchecked__array__deleter.html", "structchecked__array__deleter" ],
    [ "checked_deleter", "structchecked__deleter.html", "structchecked__deleter" ],
    [ "DdVertex", "struct_dd_vertex.html", "struct_dd_vertex" ],
    [ "DebugDrawEncoder", "struct_debug_draw_encoder.html", "struct_debug_draw_encoder" ],
    [ "DebugDrawEncoderImpl", "struct_debug_draw_encoder_impl.html", "struct_debug_draw_encoder_impl" ],
    [ "DebugDrawEncoderScopePush", "class_debug_draw_encoder_scope_push.html", "class_debug_draw_encoder_scope_push" ],
    [ "DebugDrawShared", "struct_debug_draw_shared.html", "struct_debug_draw_shared" ],
    [ "DebugMesh", "struct_debug_mesh.html", "struct_debug_mesh" ],
    [ "DebugMeshVertex", "struct_debug_mesh_vertex.html", "struct_debug_mesh_vertex" ],
    [ "DebugShapeVertex", "struct_debug_shape_vertex.html", "struct_debug_shape_vertex" ],
    [ "DebugUvVertex", "struct_debug_uv_vertex.html", "struct_debug_uv_vertex" ],
    [ "DebugVertex", "struct_debug_vertex.html", "struct_debug_vertex" ],
    [ "FontRangeMerge", "struct_font_range_merge.html", "struct_font_range_merge" ],
    [ "GeometryHandle", "struct_geometry_handle.html", "struct_geometry_handle" ],
    [ "GeometryT", "struct_geometry_t.html", "struct_geometry_t" ],
    [ "ImGui_ImplOSPP_Data", "struct_im_gui___impl_o_s_p_p___data.html", "struct_im_gui___impl_o_s_p_p___data" ],
    [ "ImGui_ImplOSPP_ViewportData", "struct_im_gui___impl_o_s_p_p___viewport_data.html", "struct_im_gui___impl_o_s_p_p___viewport_data" ],
    [ "module_data", "structmodule__data.html", "structmodule__data" ],
    [ "module_desc", "structmodule__desc.html", "structmodule__desc" ],
    [ "OcornutImguiContext", "struct_ocornut_imgui_context.html", "struct_ocornut_imgui_context" ],
    [ "Pack2D", "struct_pack2_d.html", "struct_pack2_d" ],
    [ "PackCube", "struct_pack_cube.html", "struct_pack_cube" ],
    [ "point", "structpoint.html", "structpoint" ],
    [ "Program", "struct_program.html", "struct_program" ],
    [ "range", "structrange.html", "structrange" ],
    [ "rect", "structrect.html", "structrect" ],
    [ "RectanglePacker", "class_rectangle_packer.html", "class_rectangle_packer" ],
    [ "RectPack2DT", "class_rect_pack2_d_t.html", "class_rect_pack2_d_t" ],
    [ "RectPackCubeT", "class_rect_pack_cube_t.html", "class_rect_pack_cube_t" ],
    [ "rendering_pipeline", "classrendering__pipeline.html", null ],
    [ "service", "structservice.html", "structservice" ],
    [ "size", "structsize.html", "structsize" ],
    [ "SpriteHandle", "struct_sprite_handle.html", "struct_sprite_handle" ],
    [ "SpriteT", "struct_sprite_t.html", "struct_sprite_t" ]
];